baseURL = 'https://bhojanapp.com/'
languageCode = 'en-us'
title = 'BhojanApp | Easy Restaurant Software for Billing and Management'
enableRobotsTXT = true
summaryLength=10
enableGitInfo = true
disableKinds = ['taxonomy', 'term']

[params]
  name = 'BhojanApp'
  price = '499.00'
  setupDownloadLink = 'https://bhojanapp.com/bhojan_app.exe'
  calendlyLink = 'https://calendly.com/bhojanapp-help/30min'
  logoUrl = '/img/logos/bhojanAppCharlogo.png'
  logoBannerUrl = '/img/logos/bhojanAppBanner.png'
  description = 'BhojanApp: Simple restaurant software. Easily manage your billing, create reports, and keep track of your sales all in one place. Whether you run a small eatery or a bustling restaurant, BhojanApp helps you stay organized and efficient.'
  keywords = 'BhojanApp, easy restaurant software, simple billing app, restaurant management, POS software'
  ogTitle = 'BhojanApp: Simple Restaurant Software'
  ogDescription = 'BhojanApp makes restaurant management easy. Handle bills, orders, and stock without hassle. Try it now!'
  twitterTitle = 'BhojanApp: Easy-to-Use Restaurant Software'
  twitterDescription = 'Make your restaurant work smoother with BhojanApp. Easy billing, ordering, and stock management.'
  scriptDescription = 'POS software, restaurant software, billing app, billing software, inventory management'

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params.customerLogos]
  [[params.customerLogos.items]]
    name = "Brewed Bliss Cafe"
    image = "/img/logos/1.png"
  [[params.customerLogos.items]]
    name = "Raja's Feast"
    image = "/img/logos/2.png"
  [[params.customerLogos.items]]
    name = "Mandarin Mystique"
    image = "/img/logos/3.png"
  [[params.customerLogos.items]]
    name = "Punjabi Platter"
    image = "/img/logos/4.png"
  [[params.customerLogos.items]]
    name = "Chutney Enigma"
    image = "/img/logos/5.png"
  [[params.customerLogos.items]]
    name = "Tacoste"
    image = "/img/logos/6.png"
  [[params.customerLogos.items]]
    name = "Larana"
    image = "/img/logos/7.png"
  [[params.customerLogos.items]]
    name = "Bombay Bistro"
    image = "/img/logos/8.png"

  

[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  
  [[menu.main]]
    name = "Blogs"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 3

  [[menu.footer_resource]]
    name = "Download"
    url = "/bhojan_app.exe"
    weight = 1

  [[menu.footer_resource]]
    name = "Get Started"
    url = "https://calendly.com/bhojanapp-help/30min"
    weight = 2


  [[menu.footer_link]]
    name = "Privacy"
    url = "/privacy/"
    weight = 1

  [[menu.footer_link]]
    name = "Terms"
    url = "/terms/"
    weight = 2

  [[menu.footer_link]]
    name = "Sitemap"
    url = "/sitemap.xml"
    weight = 3

    

  
  [[menu.footer_nav]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.footer_nav]]
    name = "About us"
    url = "/about/"
    weight = 2

  [[menu.footer_nav]]
    name = "Teams"
    url = "/team/"
    weight = 3


  [[menu.social_media_handles]]
    name = "Instagram"
    url = "https://www.instagram.com/tech_entrepreneurship/"
    weight = 1

  [[menu.social_media_handles]]
    name = "Twitter"
    url = "https://x.com/bhojanApp"
    weight = 2

  [[menu.social_media_handles]]
    name = "Youtube"
    url = "https://www.youtube.com/channel/UCFgYNxfPzTJibXOkm5oudUg"
    weight = 3
  